version: "3.3"

services:
  postgres_finance:
    container_name: postgres_finance
    image: postgres:12.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
    - "5432:5432"
    networks:
      - back-tier

  jaeger_ifood:
    container_name: jaeger_finance
    image: jaegertracing/all-in-one:1.17
    networks:
      - back-tier
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  prometheus_finance:
    container_name: prometheus_finance2
    image: regisflorentino/finance-prometheus
    networks:
      - back-tier
    ports:
      - "9090:9090"
  grafana-restaurante:
    container_name: grafana-finance
    image: grafana/grafana:6.5.0
    ports:
      - "3000:3000"
  quarkus_finance:
    container_name: quarkus_finance_container
    image: quarkus/quarkus-finance-jvm
    networks:
      - back-tier
    ports:
      - "8080:8080"
networks:
  back-tier: