

create table if not exists quotation
(
    id               bigint generated by default as identity
    primary key,
    buyquotation     numeric(19, 2),
    datequotation    date,
    requestid        varchar(255),
    sellquotation    numeric(19, 2),
    timestamprequest varchar(255)
    );

alter table quotation
    owner to root;